In [1]:
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
df = pd.read_csv('/content/drive/MyDrive/coding/colab_course/cities.csv')
df

     LatD   "LatM"   "LatS"  "NS"  ...   "LonS"   "EW"              "City"  "State"
0      41        5       59   "N"  ...        0    "W"        "Youngstown"       OH
1      42       52       48   "N"  ...       23    "W"           "Yankton"       SD
2      46       35       59   "N"  ...       36    "W"            "Yakima"       WA
3      42       16       12   "N"  ...        0    "W"         "Worcester"       MA
4      43       37       48   "N"  ...       11    "W"   "Wisconsin Dells"       WI
..    ...      ...      ...   ...  ...      ...    ...                 ...      ...
123    39       31       12   "N"  ...       35    "W"              "Reno"       NV
124    50       25       11   "N"  ...        0    "W"            "Regina"       SA
125    40       10       48   "N"  ...       23    "W"         "Red Bluff"       CA
126    40       19       48   "N"  ...       48    "W"           "Reading"       PA
127    41        9       35   "N"  ...       23    "W"           "Ravenna"      OH

[128 rows x 10 columns]